// Club crest URLs from football-data.org — keyed by Ukrainian team name
const CLUB_CRESTS = {
  'Арсенал':           'https://crests.football-data.org/57.png',
  'Атлетіко':          'https://crests.football-data.org/78.png',
  'Атлетік':           'https://crests.football-data.org/77.png',
  'Аталанта':          'https://crests.football-data.org/102.png',
  'Аякс':              'https://crests.football-data.org/674.png',
  'Баварія Мюнхен':    'https://crests.football-data.org/5.png',
  'Баєр Леверкузен':   'https://crests.football-data.org/3.png',
  'Барселона':         'https://crests.football-data.org/81.png',
  'Бенфіка':           'https://crests.football-data.org/1903.png',
  'Боруссія Д.':       'https://crests.football-data.org/4.png',
  'Брюгге':            'https://crests.football-data.org/851.png',
  'Вільярреал':        'https://crests.football-data.org/94.png',
  'Галатасарай':       'https://crests.football-data.org/1884.png',
  'Інтер':             'https://crests.football-data.org/108.png',
  'Копенгаген':        'https://crests.football-data.org/1887.png',
  'Ліверпуль':         'https://crests.football-data.org/64.png',
  'Манчестер Сіті':    'https://crests.football-data.org/65.png',
  'Марсель':           'https://crests.football-data.org/516.png',
  'Монако':            'https://crests.football-data.org/548.png',
  'Наполі':            'https://crests.football-data.org/113.png',
  'Ньюкасл Юнайтед':   'https://crests.football-data.org/67.png',
  'ПСВ':               'https://crests.football-data.org/672.png',
  'ПСЖ':               'https://crests.football-data.org/524.png',
  'Реал Мадрид':       'https://crests.football-data.org/86.png',
  'Спортінг':          'https://crests.football-data.org/498.png',
  'Тоттенгем':         'https://crests.football-data.org/73.png',
  'Челсі':             'https://crests.football-data.org/61.png',
  'Ювентус':           'https://crests.football-data.org/109.png',
  'Айнтрахт Ф.':       'https://crests.football-data.org/19.png',
}

export default CLUB_CRESTS
