// Club crest URLs from Supabase Storage — keyed by Ukrainian team name
const CLUB_CRESTS = {
  'Айнтрахт Ф.':             'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/eintracht-frankfurt.png',
  'Арсенал':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/arsenal.png',
  'Аталанта':                'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/atalanta.png',
  'Атлетік':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/athletic-bilbao.png',
  'Атлетіко':                'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/atletico.png',
  'Аякс':                    'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/ajax.png',
  'Баварія Мюнхен':          'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/bayern-munich.png',
  'Баєр Леверкузен':         'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/bayer-leverkusen.png',
  'Барселона':               'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/barcelona.png',
  'Бенфіка':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/benfica.png',
  'Боруссія Д.':             'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/borussia-dortmund.png',
  'Брюгге':                  'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/brugge.png',
  'Буде/Глімт':              'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/bodo-glimt.png',
  'Вільярреал':              'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/villarreal.png',
  'Галатасарай':             'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/galatasaray.png',
  'Інтер':                   'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/inter.png',
  'Кайрат Алмати':           'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/kairat.png',
  'Карабах':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/karabakh.png',
  'Копенгаген':              'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/copenhagen.png',
  'Ліверпуль':               'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/liverpool.png',
  'Манчестер Сіті':          'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/man-city.png',
  'Марсель':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/marseille.png',
  'Монако':                  'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/monaco.png',
  'Наполі':                  'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/napoli.png',
  'Ньюкасл Юнайтед':         'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/newcastle.png',
  'Олімпіакос Пірей':        'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/olympiacos.png',
  'Пафос':                   'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/pafos.png',
  'ПСВ':                     'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/psv.png',
  'ПСЖ':                     'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/psg.png',
  'Реал Мадрид':             'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/real-madrid.png',
  'Рояль Уніон СЖ':          'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/union-sg.png',
  'Славія Прага':            'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/slavia-prague.png',
  'Спортінг':                'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/sporting.png',
  'Тоттенгем':               'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/tottenham.png',
  'Челсі':                   'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/chelsea.png',
  'Ювентус':                 'https://ewzuvgxkftoivmzruuaj.supabase.co/storage/v1/object/public/club-crests/juventus.png',
}

export default CLUB_CRESTS
